services:
  # ============================================================
  # Backend Application
  # ============================================================
  backend:
    container_name: be-weather-app
    image: firmansyw30/be-weather-app:latest
    environment:
      INFISICAL_DOMAIN: ${INFISICAL_DOMAIN}
      INFISICAL_TOKEN: ${INFISICAL_TOKEN}
    ports:
      - "127.0.0.1:3000:3000"
    restart: unless-stopped

  # ============================================================
  # Frontend
  # ============================================================
  frontend:
    container_name: fe-weather-app
    image: firmansyw30/fe-weather-app:latest
    ports:
       - "127.0.0.1:8080:80"
    depends_on:
      - backend
    restart: unless-stopped
